name: Deploy NestJS Backend

on:
  push:
    branches: [ "main-prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            . ~/.bashrc
            
            cd /home/team-ronix-api/htdocs/api.team-ronix.dedyn.io

            # Reset changes & pull latest code
            git fetch --all
            git reset --hard origin/main-prod

            # Install dependencies
            npm ci --only=production

            # Generate Prisma Client
            npx prisma generate

            # Run migrations
            npx prisma migrate deploy

            # Build the application
            npm run build

            # Restart the application with PM2
            pm2 restart efl-backend || pm2 start dist/main.js --name efl-backend

            # Save PM2 configuration
            pm2 save
